---
title: "HuYuDataInsight LLC"
author: "Zhaowei Cai"
date: "2024-05-21"
output:
  pdf_document: default
  word_document: default
update: "2024-05-21"
---

(a)
```{r}
setwd("D:/AMS-SBU/HuYuDataInsight/20240521")
library(quantmod)
library(urca)
library(forecast)
library(tseries)
library(fGarch)
library(zoo)
library(tseries)
library(rugarch) 
library(stringr)
library(PerformanceAnalytics)
library(xts)
```

```{r}
data = read.csv('Moderna 5 Years.csv')
closing = data$Close # closing price
log_closing = log(data$Close)
log_return = na.omit(diff(log(data$Close))) # log return

# Visualize the data
time = as.Date(data$Date)
df = data.frame(datefield = time[2:length(time)], MRNA = log_return)
MRNA_stock = with(df, zoo(MRNA, order.by = time))
plot.zoo(MRNA_stock, col = 4, las = 1, main = "MRNA_stock log return")
```
```{r}
MRNAtimeseries <- ts(log_return, frequency = 1)
plot(MRNAtimeseries, col=4, las=1)
abline(v=c(1, 1205, 1234), lty="dotted", col=4)

data_len = length(MRNAtimeseries)
myts = subset(MRNAtimeseries, subset=rep(c(TRUE, FALSE), times=c(1204,30)))
```
## Step 1: visualize myts

```{r}
plot.zoo(myts, col=4, las=1, main="Time Series")
```

## Step 2: unit root test (augmented Dickey-Fuller) of myts

```{r}
n = length(myts)
acf(myts,main="ACF of the closing price",yaxt="n")
adf.test(myts, alternative = 'stationary')
pacf(myts,main="PACF of the closing price",yaxt="n")
```
P-value less than 0.05, reject H0, and it is stationary.
```{r}
summary(ur.df(myts, type='trend', lags=20, selectlags="BIC"))
```

## Step 3: identify lags for myts

```{r}
par(mfrow=c(1,2), mar=c(5,4,3,3))
acf(myts)
pacf(myts)
```

## Step 4: train the model with auto.arima for myts

```{r}
fit_myts = auto.arima(myts, max.p=10, max.q=10, ic="aicc",
                       seasonal=FALSE, stationary=TRUE, lambda=NULL, 
                       stepwise=FALSE, approximation=FALSE
                       )
summary(fit_myts)
```

## Step 5: fit the log return, i.e. myts

```{r}
fit_myts = arima(myts, c(2,0,2))
summary(fit_myts)
```

```{r}
forecast_myts = forecast(fit_myts, h=30, level=0.95)
plot(forecast_myts, col=4, las=1)
abline(v=c(1, 1205, 1234), lty="dotted", col=4)
lines(1205:1234, MRNAtimeseries[1205:1234], lty="dotted", col="red")
# red is observation and blue is prediction
```
## Step 6: fit the closing price, i.e. myts

```{r}
#MRNAtimeseries_1 <- ts(log_closing, frequency = 1)
#plot(JJtimeseries_1, col=4, las=1, main = "JJ_stock log closing price")
#abline(v=c(1, 1227, 1255), lty="dotted", col=4)

```

```{r}
data_len = length(JJtimeseries_1)
myts_1 = subset(JJtimeseries_1, subset=rep(c(TRUE, FALSE), times=c(1227,30)))

fit_myts_1 = arima(myts_1, c(4,1,1))
summary(fit_myts_1)
```
```{r}
forecast_myts1 = forecast(fit_myts_1, h=30, level=0.95)
print(forecast_myts1)
plot(forecast_myts1, col=4, las=1)
abline(v=c(1, 1227, 1255), lty="dotted", col=4)
lines(1227:1255, JJtimeseries_1[1227:1255], lty="dotted", col="red")
# red is observation and blue is prediction
```